FROM python:3.8-slim-buster

RUN mkdir /home/app

WORKDIR /home

RUN groupadd app && useradd --create-home --home-dir /home/app --shell /bin/bash app -g app


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
  && apt-get install -y postgresql gcc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
WORKDIR app

COPY app/requirements.txt app/requirements.txt
RUN pip install -r app/requirements.txt

USER app


