name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    container:
      image: python:3.8-slim-buster
      volumes:
        - .:/home

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt


    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    - name: Check Lint with flake8
      run: |
        python -m flake8 --check --diff app/src |
        flake8 

    - name: Black Check
      run: |
        python -m black --check --diff app/src |
        python -m black app/src

    - name: Isort Check
      run: |
        python -m isort --check --diff app |
        python -m isort app/src

    - name: Tests and Coverage with pytest
      run: |
        python -m pytest app --cov-report term --cov=app --cov-fail-under=30

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v1

    # - name: Terraform Init
    #   run: |
    #     cd infra-lambda/
    #     terraform init

    # - name: Terraform Apply
    #   run: |
    #     cd infra-lambda/
    #     terraform apply -auto-approve