name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    container:
      image: python:3.8-slim-buster
      volumes:
        - .:/app

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies and Sqlite3 Migrations

      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests and Coverage
      run: |
        python -m pytest . --cov-report term --cov=. --cov-fail-under=30

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    - name: Check Lint with flake8
      run: |
        python -m flake8 --check --diff . |
        flake8 .

    - name: Black Check
      run: |
        python -m black --check --diff . |
        python -m black .

    - name: Isort Check
      run: |
        python -m isort --check --diff . |
        python -m isort .

    - name: Tests and Coverage with pytest - over Sqlite3 temp DB
      run: |
        python -m pytest . --cov-report term --cov=. --cov-fail-under=30

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v1

    # - name: Terraform Init
    #   run: |
    #     cd infra-lambda/
    #     terraform init

    # - name: Terraform Apply
    #   run: |
    #     cd infra-lambda/
    #     terraform apply -auto-approve